services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: outdoor-spot-db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - outdoor-spot



  # Backend (Node.js + Prisma)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: outdoor-spot-backend
    working_dir: /app
    env_file:
      - ./.env
    environment:
      - PORT=${PORT}
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - postgres
    networks:
      - outdoor-spot




  # Frontend (Next.js)
  frontend:
    image: node:20-alpine
    container_name: outdoor-spot-frontend
    working_dir: /app
    env_file:
      - ./.env
    environment:
      - PORT=${FRONTEND_PORT}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    depends_on:
      - backend
    networks:
      - outdoor-spot
    command: sh -c "npm install && npm run dev"


volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
  frontend_next:

networks:
  outdoor-spot:
    driver: bridge
